/*
 * This Java source file was generated by the Gradle 'init' task.
 */
/*
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
*/

/* Browser configuration Setup.

 */

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.net.URL;

public class Linky
{

     private static int _WindowWidth = 800;
     private static int _WindowHeight = 600;
     private static String _AppTitle = "Linky - Text-Browser";
     private static int _WindowXPosition = 100;
     private static int _WindowYPosition = 100;

     public static void main( String args[] )
     {
         Coordinator browser = new Coordinator( _AppTitle,
						_WindowXPosition,
						_WindowYPosition,
						_WindowWidth,
						_WindowHeight);
	 
         browser.addWindowListener(new WindowAdapter() {
                 public void windowClosing( WindowEvent e )
                 {
                     System.exit( 0 );
                 }
             });
	 /*
	 URL url = new URL("http://stackoverflow.com");

	 try (BufferedReader reader = new BufferedReader(new InputStreamReader(url.openStream(), "UTF-8"))) {
    for (String line; (line = reader.readLine()) != null;) {
        System.out.println(line);
    }
} 
	 */
     }
 }
