/*
 * This Java source file was generated by the Gradle 'init' task.
 */
/*
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
*/

 import java.awt.*;
 import java.awt.event.*;
 import javax.swing.*;

 public class Linky
     extends JFrame
     implements ActionListener {

     private static int _WindowWidth = 800;
     private static int _WindowHeight = 600;
     private static String _AppTitle = "Linky - Text-Browser";
     private static int _WindowXPosition = 100;
     private static int _WindowYPosition = 100;

     private BorderLayout layout;

     public Linky(String appTitle,
                int windowXPosition,
                int windowYPosition,
                int windowWidth,
                int windowHeight)
     {
         super(appTitle);
         layout = new BorderLayout( windowXPosition,
                                    windowYPosition);
         Container c = getContentPane();
         c.setLayout( layout );
         setSize( windowWidth, windowHeight );
         show();
     }

     public void actionPerformed( ActionEvent e )
     {
     }

     public static void main( String args[] )
     {
         Linky linkyApp = new Linky( _AppTitle,
				     _WindowXPosition,
				     _WindowYPosition,
				     _WindowWidth,
				     _WindowHeight);
	 
         linkyApp.addWindowListener(new WindowAdapter() {
                 public void windowClosing( WindowEvent e )
                 {
                     System.exit( 0 );
                 }
             });
     }
 }
